# Week 1


In [ ]:
import numpy as np
arr = np.array([1,2,3],)
a1 = [1,2,3,4,5]
b = list([1,2,3,4])
print(arr)
print(a1)
print(b)

print(type(arr))
print(type(a1))
print(type(b))
type(b)
print(arr.dtype)

print(arr[2])
print(arr[0])
# array are mutable
arr[2] = 30
print(f'3rd element: {arr[2]}')

print(arr.shape)
print(arr.size)
matrix  = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.size)
matrix.reshape(3,2)
print(matrix)
print(matrix.shape)
print(matrix.size)



In [ ]:
a = np.array([[1,2,3],[4,5,6],[4,5,6],[4,5,6]])

print(a)
print(a.size)
print(a.shape)
b = a.reshape(6,2)
print(b)
print(b.size)
print(b.shape)
print(f'6th row and 2nd col: {b[5][1]}')
print(f'ndim: {a.ndim}')
print(f'itemsize: {a.itemsize}')
c  = np.array([[1,2,3,4,5],[1,2,3,4,7]],ndmin=3)
print(c)
print(c.shape)
print(c.ndim)

#Slicing
s1 = np.array([1,2,3,4,5,6,7,8,9])
print(s1[3:6:2])
print(s1[-1:-6:-1])

# print in reverse
print(s1[::-1])
#printing with step
print(s1[1:10:2])


In [ ]:
r1 = np.array(range(10,101,10))
print(r1)
print(r1.size)
print(r1.shape)
r2 = r1.reshape(10,1)
print(r2)
print(r2.size)
print(r2.shape)
# slicing
print(r1[::-2])


In [ ]:
# statistical functions
nums =[]
for i in range(1,100):
  # nums.append(np.random.randint(0,i))
  nums.append(np.random.randint(0,100))
print(nums)
print(np.average(nums))
print(np.median(nums))
print(np.sum(nums))
print(np.sort(nums))
print('-'*40,'matrices','-'*40)
mat1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
mat2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(mat1+mat2)
print(mat1-mat2)
print(mat1*mat2)
print(mat1/mat2)
print(np.add(mat1,mat2))
print(np.subtract(mat1,mat2))
print(np.multiply(mat1,mat2))
print(np.divide(mat1,mat2))
print('-'*40,'matrices transpose','-'*40)
t_mat1 = np.transpose(mat1)
print(t_mat1)
print(np.dot(mat1,t_mat1))



In [ ]:
mat1= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.transpose(mat1))
print(mat1.T)

In [ ]:
mat2 = np.zeros((2,2))
print(mat2)
mat3 = np.ones((2,2))
print(mat3)

In [ ]:
str_arr = ['apple','banana','cherry','cherry']
print(str_arr)
print(str_arr[1])
print(str_arr[1:3])
str_arr2 = np.array(['apple','banana','cherry'],ndmin=3)
print(str_arr2[0][0][1])



In [ ]:
# loops
nums = np.array([[1,2,3],[4,5,6]])
print(nums)
print(np.array([j for j in i for i in nums]))
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1==nums)

In [ ]:
import numpy as np

# Joining and splitting
# Joining arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
joined_arr = np.concatenate((arr1, arr2), axis=0)
print("Joined array (axis=0):")
print(joined_arr)

# Splitting arrays
parts = 2
# parts shoud split array in equal parts, eg: 3 doesn't work
split_arr = np.split(joined_arr, parts)
print("Split arrays:")
# enumerate give indexed list, idx and value
for idx, arr_part in enumerate(split_arr):
    print(f"Part {idx+1}:")
    print(arr_part)

In [ ]:
# universal functions
import numpy as np

arr = np.arange(1, 10)
print(f"Original array:\n{arr}")
# Original array:
# [1 2 3 4 5 6 7 8 9]

# Using the sqrt ufunc
print(f"\nSquare root of each element:\n{np.sqrt(arr)}")
# Square root of each element:
# [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
#  2.64575131 2.82842712 3.        ]
def test():
    print("hello\n" *30)

# %timeit - runs code multiple time , to get average execution time
%timeit test()
# %time test()



# Mathematical Methods

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.add(a, b))      # [5 7 9]
print(np.multiply(a, b)) # [ 4 10 18]
print(np.power(a, 2))    # [1 4 9]


[5 7 9]
[ 4 10 18]
[1 4 9]


In [2]:
x = np.array([1.2, 2.5, 3.8])
print(np.round(x))  # [1. 2. 4.]
print(np.floor(x))  # [1. 2. 3.]


[1. 2. 4.]
[1. 2. 3.]


# 

# Import a CSV file and perform various Statistical and Comparison operations on rows/columns.

In [ ]:
import pandas as pd
import numpy as np

df = p.read_csv