# Week 1


In [2]:
import numpy as np
arr = np.array([1,2,3],)
a1 = [1,2,3,4,5]
b = list([1,2,3,4])
print(arr)
print(a1)
print(b)

print(type(arr))
print(type(a1))
print(type(b))
type(b)
print(arr.dtype)

print(arr[2])
print(arr[0])
# array are mutable
arr[2] = 30
print(f'3rd element: {arr[2]}')

print(arr.shape)
print(arr.size)
matrix  = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.size)
matrix.reshape(3,2)
print(matrix)
print(matrix.shape)
print(matrix.size)



[1 2 3]
[1, 2, 3, 4, 5]
[1, 2, 3, 4]
<class 'numpy.ndarray'>
<class 'list'>
<class 'list'>
int64
3
1
3rd element: 30
(3,)
3
[[1 2 3]
 [4 5 6]]
(2, 3)
6
[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [3]:
a = np.array([[1,2,3],[4,5,6],[4,5,6],[4,5,6]])

print(a)
print(a.size)
print(a.shape)
b = a.reshape(6,2)
print(b)
print(b.size)
print(b.shape)
print(f'6th row and 2nd col: {b[5][1]}')
print(f'ndim: {a.ndim}')
print(f'itemsize: {a.itemsize}')
c  = np.array([[1,2,3,4,5],[1,2,3,4,7]],ndmin=3)
print(c)
print(c.shape)
print(c.ndim)

#Slicing
s1 = np.array([1,2,3,4,5,6,7,8,9])
print(s1[3:6:2])
print(s1[-1:-6:-1])

# print in reverse
print(s1[::-1])
#printing with step
print(s1[1:10:2])


[[1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
12
(4, 3)
[[1 2]
 [3 4]
 [5 6]
 [4 5]
 [6 4]
 [5 6]]
12
(6, 2)
6th row and 2nd col: 6
ndim: 2
itemsize: 8
[[[1 2 3 4 5]
  [1 2 3 4 7]]]
(1, 2, 5)
3
[4 6]
[9 8 7 6 5]
[9 8 7 6 5 4 3 2 1]
[2 4 6 8]


In [4]:
r1 = np.array(range(10,101,10))
print(r1)
print(r1.size)
print(r1.shape)
r2 = r1.reshape(10,1)
print(r2)
print(r2.size)
print(r2.shape)
# slicing
print(r1[::-2])


[ 10  20  30  40  50  60  70  80  90 100]
10
(10,)
[[ 10]
 [ 20]
 [ 30]
 [ 40]
 [ 50]
 [ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]]
10
(10, 1)
[100  80  60  40  20]


In [6]:
# statistical functions
nums =[]
for i in range(1,100):
  # nums.append(np.random.randint(0,i))
  nums.append(np.random.randint(0,100))
print(nums)
print(np.average(nums))
print(np.median(nums))
print(np.sum(nums))
print(np.sort(nums))
print('-'*40,'matrices','-'*40)
mat1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
mat2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(mat1+mat2)
print(mat1-mat2)
print(mat1*mat2)
print(mat1/mat2)
print(np.add(mat1,mat2))
print(np.subtract(mat1,mat2))
print(np.multiply(mat1,mat2))
print(np.divide(mat1,mat2))
print('-'*40,'matrices transpose','-'*40)
t_mat1 = np.transpose(mat1)
print(t_mat1)
print(np.dot(mat1,t_mat1))



[16, 3, 93, 5, 70, 24, 37, 41, 17, 91, 39, 58, 7, 91, 5, 5, 72, 33, 42, 86, 12, 97, 13, 93, 14, 38, 15, 85, 17, 22, 4, 3, 73, 55, 86, 9, 37, 48, 77, 93, 88, 97, 40, 19, 25, 22, 27, 51, 88, 83, 71, 3, 65, 56, 36, 77, 11, 83, 77, 15, 59, 62, 52, 72, 6, 51, 30, 10, 76, 70, 8, 47, 47, 96, 33, 85, 6, 12, 72, 86, 7, 75, 92, 51, 87, 8, 56, 6, 24, 65, 90, 0, 50, 90, 70, 74, 39, 85, 15]
47.717171717171716
48.0
4724
[ 0  3  3  3  4  5  5  5  6  6  6  7  7  8  8  9 10 11 12 12 13 14 15 15
 15 16 17 17 19 22 22 24 24 25 27 30 33 33 36 37 37 38 39 39 40 41 42 47
 47 48 50 51 51 51 52 55 56 56 58 59 62 65 65 70 70 70 71 72 72 72 73 74
 75 76 77 77 77 83 83 85 85 85 86 86 86 87 88 88 90 90 91 91 92 93 93 93
 96 97 97]
---------------------------------------- matrices ----------------------------------------
[[ 11  22  33  44  55]
 [ 66  77  88  99 110]]
[[ -9 -18 -27 -36 -45]
 [-54 -63 -72 -81 -90]]
[[  10   40   90  160  250]
 [ 360  490  640  810 1000]]
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]

In [7]:
mat1= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.transpose(mat1))
print(mat1.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [178]:
mat2 = np.zeros((2,2))
print(mat2)
mat3 = np.ones((2,2))
print(mat3)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [198]:
str_arr = ['apple','banana','cherry','cherry']
print(str_arr)
print(str_arr[1])
print(str_arr[1:3])
str_arr2 = np.array(['apple','banana','cherry'],ndmin=3)
print(str_arr2[0][0][1])



['apple', 'banana', 'cherry', 'cherry']
banana
['banana', 'cherry']
banana


In [217]:
# loops
nums = np.array([[1,2,3],[4,5,6]])
print(nums)
print(np.array([j for j in i for i in nums]))
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1==nums)

[[1 2 3]
 [4 5 6]]
[4 4 5 5 6 6]
[[ True  True  True]
 [False False False]]


In [ ]:
import numpy as np

# Joining and splitting
# Joining arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
joined_arr = np.concatenate((arr1, arr2), axis=0)
print("Joined array (axis=0):")
print(joined_arr)

# Splitting arrays
parts = 2
# parts shoud split array in equal parts, eg: 3 doesn't work
split_arr = np.split(joined_arr, parts)
print("Split arrays:")
# enumerate give indexed list, idx and value
for idx, arr_part in enumerate(split_arr):
    print(f"Part {idx+1}:")
    print(arr_part)

Joined array (axis=0):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Split arrays:
Part 1:
[[1 2 3]]
Part 2:
[[4 5 6]]
Part 3:
[[7 8 9]]
Part 4:
[[10 11 12]]


In [ ]:
# universal functions
import numpy as np

arr = np.arange(1, 10)
print(f"Original array:\n{arr}")
# Original array:
# [1 2 3 4 5 6 7 8 9]

# Using the sqrt ufunc
print(f"\nSquare root of each element:\n{np.sqrt(arr)}")
# Square root of each element:
# [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
#  2.64575131 2.82842712 3.        ]
def test():
    print("hello\n" *30)
%timeit test()